# Site settings
title: Eduardo's blog
email: edu.rh90@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal blog for Eduardo Ramírez. Web developer, Industrial Engineer,
  and Hotel Julieta's bassist.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ejramire.github.io" # the base hostname & protocol for your site
twitter_username: eduramirezh
github_username:  ejramire
linkedin_id: 148761809


# Build settings
markdown: kramdown
